package fr.urouen.controller;

public class HelpPage {

	public String toString() {
		return "<h1>Aide</h1>"
				+ "<h2>1 - Page d'acceuil</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td><a href=\"/restcvi\">/restcvi</a></td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>GET</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Format HTML ou XHTML valide. "+
							"Affiche la page d'accueil du projet avec les informations suivantes :" + 
							"<ul>"
							+ "<li>Nom du projet</li>"
							+ "<li>nom & prénom de l'auteur</li>"
							+ "<li>logo de l'Université de Rouen</li>"
							+"</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"
					
				+ "<h2>2 - Aide</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td><a href=\"/restcvi/help\">/restcvi/help</a></td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>GET</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Format HTML ou XHTML valide. " + 
						"Affiche la liste des opérations gérées par le service REST. " + 
						"Pour chacune des opérations proposées par le service, sont affichés : "
							+ "<ul>"
								+ "<li>URL</li>"
								+ "<li>méthode</li>"
								+ " <li>résumé de l'opération réalisée</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"

				+ "<h2>3 - Liste des CVs</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td><a href=\"/restcvi/resume\">/restcvi/resume</a></td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>GET</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Flux XML . " + 
						"Liste des CVs présents dans la base. " + 
						"Pour chaque CV, ne sont affichés que : " 
							+ "<ul>"
								+ "<li>Identifiant</li>"
								+ "<li>Nom</li>"
								+ "<li>prénom</li>"
								+ "<li>objectif (stage ou emploi)</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"
					
				+ "<h2>4 - Détail d'un CV</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td>/restcvi/resume/{id}, {id} = valeur numérique de l'identifiant</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>GET</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Flux XML conforme au schéma xsd. " + 
						"Totalité des informations enregistrées pour le CV dont la valeur de l'identifiant est id. " + 
						"Si l'identifiant est incorrect, retour d'un message d'erreur au format XML au format :\n"  
							+ "<ul>"
								+ "<li> id -> numéro de l'identifiant demandé\n</li>" 
								+ "<li> status -> ERROR</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"
					
				+ "<h2>5 - Ajout d'un CVs dans la base</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td><a href=\"/restcvi/insert\">/restcvi/insert</a></td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>POST</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Tranmis</td>"
						+ "<td>Flux XML décrivant la totalité du CV à ajouter, conforme au schéma xsd</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Flux XML. " + 
						"Le flux reçu est validé par le schéma XSD de définition des CVs. " + 
						"Si l'opération réussie, alors le CV est ajouté à la base, et sa persistance assurée. " + 
						"Le flux XML retourné contient les informations suivantes :"
							+ "<ul>"
								+ "<li> id -> numéro d'identifiant attribué au nouveau CV enregistré</li>"
								+ "<li> status -> INSERTED</li>"
							+ "</ul>"
							+"En cas d'échec de l'opération, seul la valeur de statut est retourné"  
							+ "<ul>"
								+ "<li> status -> ERROR</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"
				+ "<i>Remarque : La valeur de {id} est définie automatiquement par le service lors de l'ajout du CV dans la base</i>"
				
				+ "<h2>6 - Suppression d'un CV</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td>/restcvi/delete/{id}, {id} = valeur numérique de l'identifiant</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>DELETE</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Flux XML. " + 
						"Si l'opération a réussi, retour des informations suivantes :"
							+ "<ul>"
								+ "<li> id -> numéro d'identifiant du CV qui a été retiré</li>"
								+ "<li> status ->DELETED</li>"
							+ "</ul>"
							+"Si l'opération a échoué"  
							+ "<ul>"
								+ "<li> status -> ERROR</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>"
	
				+ "<h2>7 - Mise à jour d'un CV</h2>"
				+ "<table>"
					+ "<tr>"
						+ "<td>URL</td>"
						+ "<td>/restcvi/update/{id}, {id} = valeur numérique de l'identifiant</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Méthode</td>"
						+ "<td>PUT</td>"
					+"</tr>"
					+"<tr>"
						+ "<td>Tranmis</td>"
						+ "<td>Flux XML décrivant la totalité du CV que l'on souhaite modifier</td>"
					+"</tr>"	
					+"<tr>"
						+ "<td>Retour</td>"
						+ "<td>Flux XML. " + 
						"Le flux reçu est validé par le schéma XSD de définition des CVs. " + 
						"Si l'opération réussie, le flux XML contient les informations suivantes :"
							+ "<ul>"
								+ "<li> id -> numéro d'identifiant du CV modifié</li>"
								+ "<li> status ->UPDATED</li>"
							+ "</ul>"
							+"En cas d'échec de l'opération, seule la valeur du status est retournée"  
							+ "<ul>"
								+ "<li> status -> ERROR</li>"
							+ "</ul>"
						+ "</td>"
					+ "</tr>"
				+ "</table>";
	}
}
